### ISSUE TITLE
problem with execution

### ISSUE THREAD

**Issue by mobilemania123** [mauricioaniche/ck#10]
Exception in thread "main" java.lang.NullPointerExceptionat com.github.mauricioaniche.ck.FileUtils.getAllDirs(FileUtils.java:23)
	at com.github.mauricioaniche.ck.FileUtils.getAllDirs(FileUtils.java:11)
	at com.github.mauricioaniche.ck.CK.calculate(CK.java:52)
	at com.github.mauricioaniche.ck.Runner.main(Runner.java:18)

**Comment by mauricioaniche** [comment]
Saw it only now. Did you fix it?

**Comment by mauricioaniche** [comment]
I'll close this issue. If that happens again, let me know!
