### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 3000

### ISSUE THREAD

**Issue by jpantiuchina** [mauricioaniche/ck#4]
Hello, I am using your tool for my project. While running it on the repository https://github.com/eclipse/eclipse-collections, commit “617cd8e” I got “Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3000”

```
git clone -b master --single-branch https://github.com/eclipse/eclipse-collections
git checkout -f 617cd8e
```
And run ck program for that repository snapshot

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3000
	at org.eclipse.jdt.internal.compiler.ClassFile.generateBootstrapMethods(ClassFile.java:2965)
	at org.eclipse.jdt.internal.compiler.ClassFile.addAttributes(ClassFile.java:387)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:577)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.generateCode(TypeDeclaration.java:635)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.generateCode(CompilationUnitDeclaration.java:368)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:781)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1005)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:636)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:990)
	at com.github.mauricioaniche.ck.CK.calculate(CK.java:82)
	at com.github.mauricioaniche.ck.Runner.main(Runner.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by mauricioaniche** [comment]
Hi @jpantiuchina,

Based on the exception, it seems Eclipse JDT is not able to parse some file and crashes.

My tool probably printed out the class which the exception occurred, or at least, the last class analyzed. I guess if you try to analyze this class in separate, it will crash. 

Can you come up with a small reproducible version of the bug, so that we can write an unit test and decide what to do?
