### ISSUE TITLE
Program ends when ASTParser cannot parse Java files

### ISSUE THREAD

**Issue by lyriccoder** [mauricioaniche/ck#85]
Sometimes AST cannot be parsed (due to file with syntax error/ new syntax, given by new Java version).
If it is the case, the program crashes and methods.csv is empty:

If I set max partitions to 1, it didn't help. Setting JLS14 didn't help.

```
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getPackage0(PackageBinding.java:176)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.createPlainPackage(LookupEnvironment.java:1126)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildTypeBindings(CompilationUnitScope.java:135)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.buildTypeBindings(LookupEnvironment.java:475)
	at org.eclipse.jdt.internal.compiler.Compiler.accept(Compiler.java:340)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.accept(CompilationUnitResolver.java:186)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:334)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3464)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3175)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:536)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:638)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:634)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:293)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.resolve(LocalDeclaration.java:270)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolveStatements(AbstractMethodDeclaration.java:664)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.resolveStatements(MethodDeclaration.java:361)
	at org.eclipse.jdt.internal.compiler.ast.AbstractMethodDeclaration.resolve(AbstractMethodDeclaration.java:573)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1490)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.resolve(TypeDeclaration.java:1615)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.resolve(CompilationUnitDeclaration.java:662)
	at org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:902)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1044)
	at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:662)
	at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:1001)
	at com.github.mauricioaniche.ck.CK.calculate(CK.java:109)
	at com.github.mauricioaniche.ck.CK.calculate(CK.java:59)
	at com.github.mauricioaniche.ck.Runner.main(Runner.java:34)
```

Could you please handle the exception and continue the flow (the bad file will be just ignored and not included into csv)?
And if partitions are set to some value (not 1), you should ignore only 1 file, not the whole partition

**Comment by mauricioaniche** [comment]
Hi, @lyriccoder, thanks for the issue! That should be easy to fix.  

How are you running CK? Are you using the jar we provide directly, or writing your own Java program that calls the CK API?

**Comment by mauricioaniche** [comment]
Ah, ok, from the stack trace, I can see you are using our `Runner`, so you are calling it from the command line. Ok!

**Comment by mauricioaniche** [comment]
Hi, @lyriccoder, sorry for the slow reply. I pushed some code that should fix this issue!
